source 'https://rubygems.org'

ruby '2.4.1'

group :development, :test do
  gem 'capybara'
  gem 'rspec'
end

gem 'rake'
gem 'reek'
gem 'rubocop'
gem 'simplecov', require: false, group: :test
gem 'simplecov-console', require: false, group: :test
